### ISSUE TITLE
Zurb Foundation projects not stable

### ISSUE THREAD

**Issue by nzstephenf** [KKBOX/CompassApp#294]
Hi there,
I've tried to use the latest Zurb Foundation (5.3.1) using Compass.app on Windows 8.1.

When doing so this happens:
"error C:/Users/Stephen/Documents/test/sass/app.scss (org/jruby/RubyFile.java:613:in `chmod': No such process - No message available)"

Then all of a sudden:
No such process - No message available
org/jruby/RubyFile.java:613:in `chmod'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1257:in `atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1255:in `atomic_create_and_write_file'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/filesystem.rb:39:in `_store'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/base.rb:51:in `store'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/chain.rb:19:in `store'
org/jruby/RubyArray.java:1613:in `each'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/chain.rb:19:in `store'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:404:in `_to_tree'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:401:in `_to_tree'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:299:in `to_tree'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:182:in `compute_dependencies'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/node.rb:193:in `each'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/node.rb:192:in `each'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyArray.java:1613:in `each'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/node.rb:193:in `each'
org/jruby/RubyEnumerable.java:512:in `grep'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:178:in `compute_dependencies'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:153:in `dependencies'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:168:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:168:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:168:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:168:in `dependency_updated?'
org/jruby/RubyEnumerable.java:1473:in `any?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:129:in `dependencies_stale?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:168:in `dependency_updated?'
org/jruby/RubyProc.java:271:in `call'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:85:in `stylesheet_modified_since?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/staleness_checker.rb:73:in `stylesheet_needs_update?'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:211:in `update_stylesheets'
org/jruby/RubyArray.java:1613:in `each'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:293:in `watch'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/sass_compiler.rb:46:in `watch!'
C:/Users/Stephen/Documents/compass.app/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/watch_project.rb:41:in `perform'
file:/C:/Users/Stephen/Documents/compass.app/compass-app.jar!/app_watcher.rb:12:in `watch!'
file:/C:/Users/Stephen/Documents/compass.app/compass-app.jar!/ui/tray.rb:447:in `watch'

**Comment by nzstephenf** [comment]
Also - this is a fresh project so this is what happens when I start off a new project when trying to use the Zurb Foundation Framework.

**Comment by hlb** [comment]
it seems you have some permission error. Please try to create a new project in c: and move all your files into it.

**Comment by intrigue** [comment]
I have the same problem. Project created in C: and still get the errors above. I installed the Bootstrap-sass with no problems at all
