### ISSUE TITLE
Errors trying to import Compass

### ISSUE THREAD

**Issue by SeanLatimer** [KKBOX/CompassApp#298]
It compiles Sass with no problems, however when I try to import Compass it gives this error and fails to compile.

```css
/*
Errno::ESRCH: No such process - No message available

Backtrace:
org/jruby/RubyFile.java:613:in `chmod'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1257:in `atomic_create_and_write_file'
org/jruby/ext/thread/Mutex.java:149:in `synchronize'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/util.rb:1255:in `atomic_create_and_write_file'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/filesystem.rb:39:in `_store'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/base.rb:51:in `store'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/chain.rb:19:in `store'
org/jruby/RubyArray.java:1613:in `each'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/cache_stores/chain.rb:19:in `store'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:404:in `_to_tree'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:299:in `to_tree'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
org/jruby/RubyArray.java:2412:in `map'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
org/jruby/RubyArray.java:2412:in `map'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
org/jruby/RubyArray.java:2412:in `map'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:325:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:88:in `with_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:322:in `visit_import'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:115:in `with_frame'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/stack.rb:79:in `with_base'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:158:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
org/jruby/RubyArray.java:2412:in `map'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:52:in `visit_children'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:167:in `visit_children'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/base.rb:36:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:157:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/visitors/perform.rb:8:in `visit'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/root_node.rb:36:in `css_tree'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/tree/root_node.rb:20:in `render'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/engine.rb:268:in `render'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:17:in `render'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:29:in `with_import_scope'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/compass-import-once-1.0.5/lib/compass/import-once/engine.rb:16:in `render'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:492:in `update_stylesheet'
org/jruby/RubyMethod.java:128:in `call'
file:/H:/Portable Workspace/Programs/compass.app/compass-app.jar!/hook/compass_patch.rb:108:in `update_stylesheet'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:215:in `update_stylesheets'
org/jruby/RubyArray.java:1613:in `each'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:209:in `update_stylesheets'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:470:in `on_file_changed'
H:/Portable Workspace/Programs/compass.app/lib/ruby/compass_1.0/sass-3.4.13/lib/sass/plugin/compiler.rb:328:in `watch'
org/jruby/RubyProc.java:271:in `call'
H:/Portable Workspace/Programs/compass.app/lib/ruby/jruby/listen-1.3.1-patched/lib/listen/listener.rb:252:in `on_change'
H:/Portable Workspace/Programs/compass.app/lib/ruby/jruby/listen-1.3.1-patched/lib/listen/listener.rb:290:in `initialize_adapter'
org/jruby/RubyProc.java:271:in `call'
H:/Portable Workspace/Programs/compass.app/lib/ruby/jruby/listen-1.3.1-patched/lib/listen/adapters/polling.rb:48:in `poll_changed_directories'
H:/Portable Workspace/Programs/compass.app/lib/ruby/jruby/listen-1.3.1-patched/lib/listen/adapter.rb:297:in `start_poller'
*/
```

**Comment by hlb** [comment]
@SeanLatimer it seems you have some permission error. Please try to create a new project in c: and move all your files into it.

**Comment by SpecSilentSean** [comment]
@hlb same problem on C drive, I found I can import "compass/css3" etc, it only errors when I try to import "compass"

**Comment by hlb** [comment]
@SpecSilentSean does it happen with whole new project created by Compass.app?

**Comment by SpecSilentSean** [comment]
@hlb Yes, it happens with new projects
