### ISSUE TITLE
CompassApp fresh install on Mac Yosemite, DOA

### ISSUE THREAD

**Issue by cagedartist** [KKBOX/CompassApp#299]
no such file to load -- sass-globbing
org/jruby/RubyKernel.java:1071:in `require'
/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/require_patch.rb:6:in `require'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-core-1.0.3/lib/compass/configuration/data.rb:179:in `require'
/Users/bmelvin/Development/edu/berklee/docroot/sites/all/themes/suite_222/config.rb:2:in `parse_string'
org/jruby/RubyKernel.java:1107:in `eval'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/serialization.rb:24:in `parse_string'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/serialization.rb:15:in `_parse'
org/jruby/RubyIO.java:1181:in `open'
org/jruby/RubyKernel.java:349:in `open'
/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:35:in `open'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/serialization.rb:14:in `_parse'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/file_data.rb:7:in `new_from_file'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-core-1.0.3/lib/compass/configuration/inheritance.rb:207:in `with_defaults'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/file_data.rb:6:in `new_from_file'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/helpers.rb:19:in `configuration_for'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/configuration/helpers.rb:69:in `add_project_configuration'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/project_base.rb:37:in `add_project_configuration'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/project_base.rb:25:in `configure!'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/project_base.rb:15:in `initialize'
/Applications/compass.app/Contents/Resources/lib/ruby/compass_1.0/compass-1.0.3/lib/compass/commands/update_project.rb:41:in `initialize'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:431:in `watch'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/app.rb:230:in `try'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:424:in `watch'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:178:in `open_dir_handler'
anon_class315809246_76659513.gen:13:in `handleEvent'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/ui/tray.rb:70:in `run'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:129:in `run_tray'
file:/Applications/compass.app/Contents/Java/compass-app.jar!/main.rb:145:in `(root)'
org/jruby/RubyKernel.java:1071:in `require'
/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1:in `(root)'
/Applications/compass.app/Contents/Java/lib/java/jruby-complete.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54:in `require'

**Comment by hlb** [comment]
@cagedartist Compass.app does not support sass-globbing by default. Maybe you can try to install it to Compass.app: https://github.com/KKBOX/CompassApp/wiki/Using-Compass-Extensions

**Comment by m2gleason** [comment]
@hlb already did this but still not working. can you help me on this? please.

**Comment by m2gleason** [comment]
hello @cagedartist, did you already solve this?
