### ISSUE TITLE
Build not working on Mac OS 10.10.3 Yosemite

### ISSUE THREAD

**Issue by FFIN** [KKBOX/CompassApp#301]
When I run `bin/startJar-osx64.sh` I get following error.

```
cp lib/java/jruby-complete.jar package/jar/lib/java/jruby-complete.jar
Exception in thread "main" java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
``` 
Any thoughts?
Thanks in Advace!

My environment:
```
ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]

jruby -v
jruby 1.7.20 (1.9.3p551) 2015-05-04 3086e6a on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [darwin-x86_64]

```

**Comment by hlb** [comment]
@FFIN 

* install rvm
* install jruby 1.7.19

in compass.app folder, do the following:

* `gem install bundler`
* `bundle install`
* run `bin/start-osx.sh`

**Comment by FFIN** [comment]
Thanks for quick replay @hlb 

I tried that with no luck at all.

```
rvm --version
rvm version 1.07

jruby -v
jruby 1.7.19 (1.9.3p551) 2015-01-29 20786bd on Java HotSpot(TM) 64-Bit Server VM 1.7.0_79-b15 +jit [darwin-x86_64]
```

`bin/start-osx.sh` is working though.

**Comment by hlb** [comment]
@FFIN weird, any error message?

**Comment by FFIN** [comment]
Well @hlb ,

Just this.

```
Exception in thread "main" java.lang.ClassFormatError: Truncated class file
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by FFIN** [comment]
Just a food of thought.
I used rawr 1.8.3 since 1.6.6 is throwing this error.

```
/Library/Ruby/Gems/2.0.0/gems/rawr-1.6.6/lib/zip/zip.rb:28:in `<module:Zip>': Use RbConfig instead of obsolete and deprecated Config.
/Library/Ruby/Gems/2.0.0/gems/rawr-1.6.6/lib/zip/zip.rb:28:in `<module:Zip>': Use RbConfig instead of obsolete and deprecated Config.
```

I tried with 1.6.6 but nothing changes.

**Comment by FFIN** [comment]
@hlb I've managed to make it work.

`rawr install` in CompassApp folder then edit couple of files,
it's all working fine with environment bellow.

If you need a pull request, just let me know.
I'll be happy to send it.

```
ruby 2.0.0p481
jruby 1.7.20
rake 10.3.2
builder 3.2.2
diff-lcs 1.1.3
i18n 0.6.11
faker 1.4.3
hoe 3.12.0
rubyzip 1.1.6
s4t-utils 1.0.4
xml-simple 1.1.4
user-choices 1.1.6.1
rawr 1.8.3 (was 1.6.6)
rspec-core 2.12.2
rspec-expectations 2.12.1
rspec-mocks 2.12.2
rspec 2.12.0
bundler 1.9.9
```

**Comment by hlb** [comment]
@FFIN please do! :)
